server:
  port: 8080

rsa:
  public-key: classpath:/certs/public.pem
  private-key: classpath:/certs/private.pem

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/hermes
    username: root
    password: Kingmaster7+
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true